In [1]:
import numpy as np

# Getting valid words and user input

In [2]:
def get_all_valid_words():
    filename = "data/valid-words.txt"
    with open(filename, mode="r") as f:
        lines = f.read().split()

    words = np.char.array([list(word) for word in lines])
    return words

words = get_all_valid_words()
words

chararray([['a', 'a', 'h', 'e', 'd'],
           ['a', 'a', 'l', 'i', 'i'],
           ['a', 'a', 'r', 'g', 'h'],
           ...,
           ['z', 'y', 'g', 'o', 'n'],
           ['z', 'y', 'm', 'e', 's'],
           ['z', 'y', 'm', 'i', 'c']], dtype='<U1')

In [3]:
def get_guess_colors():
    guess = input("\nGuess:  ")
    colors = input("Colors: ")

    guess_vector = np.char.array(list(guess))
    colors_vector = np.char.array(list(colors))

    return (guess_vector, colors_vector)

guess, colors = get_guess_colors()
guess, colors


Guess:  crane
Colors: gbbyg


(chararray(['c', 'r', 'a', 'n', 'e'], dtype='<U1'),
 chararray(['g', 'b', 'b', 'y', 'g'], dtype='<U1'))

# Filter

## Green

In [4]:
green_letter_mask = (colors == "g")
green_word_mask = np.all(words[:, green_letter_mask] == guess[green_letter_mask], axis=1)

words[green_word_mask]

chararray([['c', 'a', 'b', 'l', 'e'],
           ['c', 'a', 'b', 'r', 'e'],
           ['c', 'a', 'c', 'h', 'e'],
           ['c', 'a', 'd', 'e', 'e'],
           ['c', 'a', 'd', 'g', 'e'],
           ['c', 'a', 'd', 'i', 'e'],
           ['c', 'a', 'd', 'r', 'e'],
           ['c', 'a', 'e', 's', 'e'],
           ['c', 'a', 'l', 'v', 'e'],
           ['c', 'a', 'n', 'o', 'e'],
           ['c', 'a', 'p', 'l', 'e'],
           ['c', 'a', 'r', 'l', 'e'],
           ['c', 'a', 'r', 's', 'e'],
           ['c', 'a', 'r', 't', 'e'],
           ['c', 'a', 'r', 'v', 'e'],
           ['c', 'a', 's', 't', 'e'],
           ['c', 'a', 'u', 's', 'e'],
           ['c', 'a', 'v', 'i', 'e'],
           ['c', 'e', 'a', 's', 'e'],
           ['c', 'e', 'a', 'z', 'e'],
           ['c', 'e', 'n', 's', 'e'],
           ['c', 'e', 'r', 'g', 'e'],
           ['c', 'e', 'r', 'n', 'e'],
           ['c', 'e', 's', 's', 'e'],
           ['c', 'e', 'z', 'v', 'e'],
           ['c', 'h', 'a', 'c', 'e'],
           [

## Yellow

In [5]:
guess, colors

(chararray(['c', 'r', 'a', 'n', 'e'], dtype='<U1'),
 chararray(['g', 'b', 'b', 'y', 'g'], dtype='<U1'))

In [6]:
words

chararray([['a', 'a', 'h', 'e', 'd'],
           ['a', 'a', 'l', 'i', 'i'],
           ['a', 'a', 'r', 'g', 'h'],
           ...,
           ['z', 'y', 'g', 'o', 'n'],
           ['z', 'y', 'm', 'e', 's'],
           ['z', 'y', 'm', 'i', 'c']], dtype='<U1')

In [7]:
letter_not_at_index_mask = np.all(words[:, ~green_letter_mask] != guess[~green_letter_mask], axis=1)
words[letter_not_at_index_mask]

chararray([['a', 'a', 'h', 'e', 'd'],
           ['a', 'a', 'l', 'i', 'i'],
           ['a', 'a', 'r', 'g', 'h'],
           ...,
           ['z', 'y', 'g', 'o', 'n'],
           ['z', 'y', 'm', 'e', 's'],
           ['z', 'y', 'm', 'i', 'c']], dtype='<U1')

In [8]:
not_green_letters = guess[~green_letter_mask]
not_green_colors = colors[~green_letter_mask]
not_green_letters, not_green_colors

(chararray(['r', 'a', 'n'], dtype='<U1'),
 chararray(['b', 'b', 'y'], dtype='<U1'))

In [9]:
unique_not_green_letters, unique_not_green_inds = np.unique(not_green_letters, return_index=True)
unique_not_green_colors = not_green_colors[unique_not_green_inds]
unique_not_green_letters, unique_not_green_inds, unique_not_green_colors

(chararray(['a', 'n', 'r'], dtype='<U1'),
 array([1, 2, 0], dtype=int64),
 chararray(['b', 'y', 'b'], dtype='<U1'))

In [10]:
unique_yellow_letter_mask = unique_not_green_colors == "y"
unique_yellow_letters = unique_not_green_letters[unique_yellow_letter_mask]
unique_yellow_letters

chararray(['n'], dtype='<U1')

In [11]:
yellow_letter_count_limits = (not_green_letters == unique_yellow_letters[:, np.newaxis]).sum(axis=1)
yellow_letter_count_limits

array([1])

In [12]:
letter_count_limits = np.zeros(unique_not_green_letters.size, dtype=np.int32)
letter_count_limits[unique_yellow_letter_mask] = yellow_letter_count_limits
letter_count_limits

array([0, 1, 0])

In [13]:
words_not_green_letters = words[:, ~green_letter_mask]
words_not_green_letters

chararray([['a', 'h', 'e'],
           ['a', 'l', 'i'],
           ['a', 'r', 'g'],
           ...,
           ['y', 'g', 'o'],
           ['y', 'm', 'e'],
           ['y', 'm', 'i']], dtype='<U1')

In [14]:
unique_not_green_letters[:, np.newaxis, np.newaxis]

chararray([[['a']],

           [['n']],

           [['r']]], dtype='<U1')

In [15]:
letter_counts = (words_not_green_letters == unique_not_green_letters[:, np.newaxis, np.newaxis]).sum(axis=2).T
letter_counts

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 1],
       ...,
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [16]:
yellow_above_count_limits_mask = (
    letter_counts[:, unique_yellow_letter_mask] >= letter_count_limits[unique_yellow_letter_mask]
).all(axis=1)
words[yellow_above_count_limits_mask]

chararray([['a', 'b', 'a', 'n', 'd'],
           ['a', 'b', 'u', 'n', 'a'],
           ['a', 'b', 'u', 'n', 'e'],
           ...,
           ['z', 'o', 'n', 'e', 's'],
           ['z', 'o', 'n', 'k', 's'],
           ['z', 'o', 'o', 'n', 's']], dtype='<U1')

## Black

In [17]:
letter_counts

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 1],
       ...,
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [18]:
letter_count_limits

array([0, 1, 0])

In [19]:
black_below_count_limits_mask = (
    letter_counts[:, ~unique_yellow_letter_mask] <= letter_count_limits[~unique_yellow_letter_mask]
).all(axis=1)
words[black_below_count_limits_mask]

chararray([['a', 'b', 'b', 'e', 'd'],
           ['a', 'b', 'b', 'e', 's'],
           ['a', 'b', 'b', 'e', 'y'],
           ...,
           ['z', 'y', 'g', 'o', 'n'],
           ['z', 'y', 'm', 'e', 's'],
           ['z', 'y', 'm', 'i', 'c']], dtype='<U1')

## Apply Masks

In [20]:
words[green_word_mask & letter_not_at_index_mask & yellow_above_count_limits_mask & black_below_count_limits_mask]

chararray([['c', 'e', 'n', 's', 'e'],
           ['c', 'o', 'n', 'g', 'e'],
           ['c', 'o', 'n', 't', 'e']], dtype='<U1')

## Full Filter

In [21]:
def get_possible_words(guess, colors, words):
    possible_words = words.copy()
    
    # Green.
    green_letter_mask = (colors == "g")
    green_word_mask = np.all(possible_words[:, green_letter_mask] == guess[green_letter_mask], axis=1)

    possible_words = possible_words[green_word_mask]
    
    # Yellow and Black: letter not at ind.
    letter_not_at_index_mask = np.all(possible_words[:, ~green_letter_mask] != guess[~green_letter_mask], axis=1)
    possible_words = possible_words[letter_not_at_index_mask]
    
    # Letter count limits.
    not_green_letters = guess[~green_letter_mask]
    not_green_colors = colors[~green_letter_mask]
    
    unique_not_green_letters, unique_not_green_inds = np.unique(not_green_letters, return_index=True)
    unique_not_green_colors = not_green_colors[unique_not_green_inds]
    
    unique_yellow_letter_mask = unique_not_green_colors == "y"
    unique_yellow_letters = unique_not_green_letters[unique_yellow_letter_mask]
    
    yellow_letter_count_limits = (not_green_letters == unique_yellow_letters[:, np.newaxis]).sum(axis=1)
    
    letter_count_limits = np.zeros(unique_not_green_letters.size, dtype=np.int32)
    letter_count_limits[unique_yellow_letter_mask] = yellow_letter_count_limits
    
    # Letter counts.
    possible_words_not_green_letters = possible_words[:, ~green_letter_mask]
    
    letter_counts = (
        possible_words_not_green_letters == unique_not_green_letters[:, np.newaxis, np.newaxis]
    ).sum(axis=2).T
    
    # Yellow mask.
    yellow_above_count_limits_mask = (
        letter_counts[:, unique_yellow_letter_mask] >= letter_count_limits[unique_yellow_letter_mask]
    ).all(axis=1)
    
    # Black mask.
    black_below_count_limits_mask = (
        letter_counts[:, ~unique_yellow_letter_mask] <= letter_count_limits[~unique_yellow_letter_mask]
    ).all(axis=1)
    
    # Apply Yellow and Black masks.
    possible_words = possible_words[yellow_above_count_limits_mask & black_below_count_limits_mask]
    
    return possible_words

# Rank

In [22]:
import itertools

In [23]:
possible_colors = np.char.array(list(itertools.product("gyb", repeat=5)))
possible_colors

chararray([['g', 'g', 'g', 'g', 'g'],
           ['g', 'g', 'g', 'g', 'y'],
           ['g', 'g', 'g', 'g', 'b'],
           ...,
           ['b', 'b', 'b', 'b', 'g'],
           ['b', 'b', 'b', 'b', 'y'],
           ['b', 'b', 'b', 'b', 'b']], dtype='<U1')

In [24]:
def rank_words(words):
    predicted_remaining_words = np.zeros(words.shape[0])

    print(f"\nRanking {words.shape[0]} words:")
    for (i, guess) in enumerate(words):
        if (i % 25 == 0):
            print(f"Ranking word: {i}")
        
        total_remaining_words = 0
        for colors in possible_colors:
            n_possible_words = get_possible_words(guess, colors, words).shape[0]
            total_remaining_words += (n_possible_words / words.shape[0]) * n_possible_words

        predicted_remaining_words[i] = total_remaining_words

    sorted_inds = np.argsort(predicted_remaining_words)
    
    return (words[sorted_inds], predicted_remaining_words[sorted_inds])

# Show words

In [25]:
def show_words(words, predicted_remaining_words, n_words):
    print("\nRanked Words:")
    for i in range(min(words.shape[0], n_words)):
        print(f"{i}. {''.join(words[i])}   {predicted_remaining_words[i]}")

# Run

In [26]:
words = get_all_valid_words()

print("----------WORDLE SOLVER----------")

cont = True
while (cont):
    guess, colors = get_guess_colors()
    words = get_possible_words(guess, colors, words)
    
    sorted_words, predicted_remaining_words = rank_words(words)
    show_words(sorted_words, predicted_remaining_words, 15)
    
    if (words.shape[0] == 1):
        print(f"\n{''.join(words[0])} is the word!")
        cont = False
    elif (words.shape[0] == 0):
        print(f"\nNo words match that description!")
        cont = False
        
print("\nThanks for playing!")

----------WORDLE SOLVER----------

Guess:  salet
Colors: gggbb

Ranking 13 words:
Ranking word: 0

Ranked Words:
0. salal   4.384615384615385
1. salol   4.384615384615385
2. salpa   4.384615384615385
3. salop   4.538461538461538
4. salsa   5.461538461538462
5. salps   6.538461538461538
6. salad   6.6923076923076925
7. salon   6.6923076923076925
8. salvo   7.0
9. salic   7.923076923076923
10. salix   7.923076923076923
11. sally   8.076923076923077
12. salmi   8.076923076923077

Guess:  salad
Colors: gggyb

Ranking 2 words:
Ranking word: 0

Ranked Words:
0. salpa   1.0
1. salsa   1.0

Guess:  salsa
Colors: ggggg

Ranking 1 words:
Ranking word: 0

Ranked Words:
0. salsa   1.0

salsa is the word!

Thanks for playing!
